version: '0.1'
services:
  conductor:
    container_name: conductor
    image: quay.io/debezium/platform-conductor:nightly
    pull_policy: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_USERNAME: conductor
      QUARKUS_DATASOURCE_PASSWORD: conductor
      QUARKUS_DATASOURCE_JDBC_URL:  jdbc:postgresql://postgres:5432/conductor
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:3000
  postgres:
    container_name: postgres
    image: quay.io/debezium/postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: conductor
      POSTGRES_PASSWORD: conductor
      POSTGRES_DB: conductor
  stage:
    depends_on:
      - conductor
    container_name: stage
    image: quay.io/debezium/platform-stage:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      CONDUCTOR_URL: http://localhost:8080